# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCPP2(object):
    def setupUi(self, MCPP2):
        MCPP2.setObjectName("MCPP2")
        MCPP2.resize(443, 180)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/MCPP.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MCPP2.setWindowIcon(icon)

        self.retranslateUi(MCPP2)
        QtCore.QMetaObject.connectSlotsByName(MCPP2)

    def retranslateUi(self, MCPP2):
        _translate = QtCore.QCoreApplication.translate
        MCPP2.setWindowTitle(_translate("MCPP2", "MCPP"))
import minecraft_rc
