# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCPP(object):
    def setupUi(self, MCPP):
        MCPP.setObjectName("MCPP")
        MCPP.resize(255, 221)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/MCPP.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MCPP.setWindowIcon(icon)
        MCPP.setStyleSheet("background-image: url(:/background/bg32.png);")
        self.centralwidget = QtWidgets.QWidget(MCPP)
        self.centralwidget.setObjectName("centralwidget")
        self.SelectB = QtWidgets.QPushButton(self.centralwidget)
        self.SelectB.setEnabled(True)
        self.SelectB.setGeometry(QtCore.QRect(10, 10, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Minecraft Rus")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.SelectB.setFont(font)
        self.SelectB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SelectB.setAutoFillBackground(False)
        self.SelectB.setStyleSheet("QPushButton{\n"
"    height: 61px;\n"
"    width: 231px;\n"
"    text-decoration: none;\n"
"    text-align: center;\n"
"    color: white;\n"
"    background: url(:/buttons/btn.png) no-repeat;\n"
"    line-height: 26px;\n"
"    border: 2px solid black;\n"
"    padding-top: 6px;}\n"
"QPushButton:Hover{\n"
"    border: 2px solid white;}\n"
"QPushButton:Focus{\n"
"   outline: none;\n"
"   border: none;}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectB.setIcon(icon1)
        self.SelectB.setIconSize(QtCore.QSize(16, 16))
        self.SelectB.setDefault(False)
        self.SelectB.setFlat(True)
        self.SelectB.setObjectName("SelectB")
        self.ConvertB = QtWidgets.QPushButton(self.centralwidget)
        self.ConvertB.setGeometry(QtCore.QRect(10, 80, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Minecraft Rus")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.ConvertB.setFont(font)
        self.ConvertB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ConvertB.setAutoFillBackground(False)
        self.ConvertB.setStyleSheet("QPushButton{\n"
"    height: 61px;\n"
"    width: 231px;\n"
"    text-decoration: none;\n"
"    text-align: center;\n"
"    color: white;\n"
"    background: url(:/buttons/btn.png) no-repeat;\n"
"    line-height: 26px;\n"
"    border: 2px solid black;\n"
"    padding-top: 6px;}\n"
"QPushButton:Hover{\n"
"    border: 2px solid white;}\n"
"QPushButton:Focus{\n"
"   outline: none;\n"
"   border: none;}\n"
"\n"
"")
        icon = QtGui.QIcon.fromTheme(",")
        self.ConvertB.setIcon(icon)
        self.ConvertB.setIconSize(QtCore.QSize(16, 16))
        self.ConvertB.setDefault(False)
        self.ConvertB.setFlat(True)
        self.ConvertB.setObjectName("ConvertB")
        self.SettingsB = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsB.setGeometry(QtCore.QRect(10, 150, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Minecraft Rus")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.SettingsB.setFont(font)
        self.SettingsB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SettingsB.setAutoFillBackground(False)
        self.SettingsB.setStyleSheet("QPushButton{\n"
"    height: 61px;\n"
"    width: 231px;\n"
"    text-decoration: none;\n"
"    text-align: center;\n"
"    color: white;\n"
"    background: url(:/buttons/btn.png) no-repeat;\n"
"    line-height: 26px;\n"
"    border: 2px solid black;\n"
"    padding-top: 6px;}\n"
"QPushButton:Hover{\n"
"    border: 2px solid white;}\n"
"QPushButton:Focus{\n"
"   outline: none;\n"
"   border: none;}\n"
"\n"
"")
        icon = QtGui.QIcon.fromTheme(",")
        self.SettingsB.setIcon(icon)
        self.SettingsB.setIconSize(QtCore.QSize(16, 16))
        self.SettingsB.setDefault(False)
        self.SettingsB.setFlat(True)
        self.SettingsB.setObjectName("SettingsB")
        MCPP.setCentralWidget(self.centralwidget)

        self.retranslateUi(MCPP)
        QtCore.QMetaObject.connectSlotsByName(MCPP)

    def retranslateUi(self, MCPP):
        _translate = QtCore.QCoreApplication.translate
        MCPP.setWindowTitle(_translate("MCPP", "MCPP"))
        self.SelectB.setText(_translate("MCPP", "Choose pack"))
        self.ConvertB.setText(_translate("MCPP", "Convert"))
        self.SettingsB.setText(_translate("MCPP", "Settings..."))
import minecraft_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MCPP = QtWidgets.QMainWindow()
    ui = Ui_MCPP()
    ui.setupUi(MCPP)
    MCPP.show()
    sys.exit(app.exec_())
